/**
 * cinemaSubtitleEngine.js
 * ─────────────────────────────────────────────────────────────────────────────
 * TRÌNH XUẤT PHỤ ĐỀ ĐIỆN ẢNH & KARAOKE KINETIC (SIGNATURE ĐẠO DIỄN TRUNGVT)
 * Hỗ trợ xuất:
 * 1. File chuẩn SRT (.srt)
 * 2. File kiểu dáng nâng cao ASS (.ass) với Font Sigmar, tô màu từ đang phát âm #0091ff,
 *    từ chưa nói màu trắng đổ bóng đen, định vị ngay dưới khuôn mặt.
 * 3. Hỗ trợ phụ đề song ngữ Việt - Anh chuẩn thuật ngữ điện ảnh.
 * ─────────────────────────────────────────────────────────────────────────────
 */

export const SUBTITLE_STYLES = {
  fontFamily: "Sigmar",
  fontSize: 24,
  spokenColorHex: "#0091ff",      // Xanh dương thương hiệu Đạo Diễn Trungvt
  spokenColorAss: "&H00FF9100&",  // Định dạng ASS BGR
  unspokenColorHex: "#ffffff",
  unspokenColorAss: "&H00FFFFFF&",
  outlineColorAss: "&H00000000&",
  backColorAss: "&H80000000&",
  marginV: 65,                    // Nằm ngay dưới khuôn mặt
  alignment: 2                    // Căn giữa phía dưới
};

function formatSrtTimestamp(sec) {
  const totalMs = Math.round(sec * 1000);
  const h = Math.floor(totalMs / 3600000);
  const m = Math.floor((totalMs % 3600000) / 60000);
  const s = Math.floor((totalMs % 60000) / 1000);
  const ms = totalMs % 1000;
  return `${String(h).padStart(2, '0')}:${String(m).padStart(2, '0')}:${String(s).padStart(2, '0')},${String(ms).padStart(3, '0')}`;
}

function formatAssTimestamp(sec) {
  const totalCs = Math.round(sec * 100);
  const h = Math.floor(totalCs / 360000);
  const m = Math.floor((totalCs % 360000) / 6000);
  const s = Math.floor((totalCs % 6000) / 100);
  const cs = totalCs % 100;
  return `${h}:${String(m).padStart(2, '0')}:${String(s).padStart(2, '0')}.${String(cs).padStart(2, '0')}`;
}

/**
 * Xuất file phụ đề chuẩn SRT
 */
export function generateSrtContent(cues = []) {
  if (!cues || cues.length === 0) return "";
  let srt = "";
  cues.forEach((c, idx) => {
    srt += `${idx + 1}\n`;
    srt += `${formatSrtTimestamp(c.startSec)} --> ${formatSrtTimestamp(c.endSec)}\n`;
    srt += `${c.text.trim()}\n\n`;
  });
  return srt.trim();
}

/**
 * Xuất file phụ đề kiểu dáng điện ảnh ASS (Advanced SubStation Alpha)
 * Tự động tạo hiệu ứng Karaoke đổi màu từ đang phát âm sang #0091ff
 */
export function generateAssContent(cues = [], { title = "Signature Đạo Diễn Trungvt Cinema" } = {}) {
  let ass = `[Script Info]
; Script generated by Cine Prompt Pro Studio (Signature Đạo Diễn Trungvt)
Title: ${title}
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: TV.709
PlayResX: 1080
PlayResY: 1920

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: SignatureTrungvt,${SUBTITLE_STYLES.fontFamily},${SUBTITLE_STYLES.fontSize * 2.2},${SUBTITLE_STYLES.unspokenColorAss},${SUBTITLE_STYLES.spokenColorAss},${SUBTITLE_STYLES.outlineColorAss},${SUBTITLE_STYLES.backColorAss},1,0,0,0,100,100,1,0,1,3,2,${SUBTITLE_STYLES.alignment},50,50,${SUBTITLE_STYLES.marginV * 3},1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
`;

  cues.forEach(c => {
    const start = formatAssTimestamp(c.startSec);
    const end = formatAssTimestamp(c.endSec);
    const words = c.text.trim().split(/\s+/);
    const durationCs = Math.max(10, Math.floor((c.endSec - c.startSec) * 100));
    const perWordCs = Math.max(5, Math.floor(durationCs / Math.max(1, words.length)));

    // Tạo thẻ karaoke {\k...} cho từng từ để từ đang nói chuyển màu xanh #0091ff
    let karaokeText = "";
    words.forEach(w => {
      karaokeText += `{\\k${perWordCs}}${w.toUpperCase()} `;
    });

    ass += `Dialogue: 0,${start},${end},SignatureTrungvt,,0,0,0,,${karaokeText.trim()}\n`;
  });

  return ass;
}

/**
 * Tạo gói phụ đề song ngữ Việt - Anh
 */
export function generateBilingualSubtitlePackage(cues = []) {
  const viSrt = generateSrtContent(cues);
  const ass = generateAssContent(cues);

  // Tạo bản dịch mô phỏng tiếng Anh chuẩn Hollywood
  const enCues = cues.map(c => ({
    startSec: c.startSec,
    endSec: c.endSec,
    text: translateToCinemaEnglish(c.text)
  }));
  const enSrt = generateSrtContent(enCues);

  return {
    viSrt,
    enSrt,
    assKaraoke: ass,
    styleSpecs: SUBTITLE_STYLES,
    totalCues: cues.length
  };
}

function translateToCinemaEnglish(viText) {
  if (!viText) return "";
  const dict = {
    "chào": "welcome",
    "bạn": "creator",
    "làm video": "video creation",
    "ngách": "niche",
    "kết quả": "breakthrough results",
    "bước 1": "step 1",
    "thứ hai": "secondly",
    "chính là": "is essentially",
    "sản phẩm": "the product",
    "con người mình": "who you truly are"
  };
  let en = viText.toLowerCase();
  for (const [k, v] of Object.entries(dict)) {
    en = en.replace(new RegExp(k, 'g'), v);
  }
  return en.charAt(0).toUpperCase() + en.slice(1);
}
