#!/usr/bin/env node
/**
 * Daily Standup Runner (60-Second Executive Sync)
 * Aggregates status across all active AI Staff:
 *  - GTM Engineer (gtm-engineer)
 *  - SEO & AEO Employee (seo-employee)
 *  - Social Media Employee (social-media-employee)
 * 
 * Generates terminal report and updates STANDUP_LATEST.md
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const staffDir = path.resolve(__dirname, '../../ai-staff');
const outputFile = path.join(staffDir, 'STANDUP_LATEST.md');

console.log('\n======================================================');
console.log('⚡ AI STAFF 60-SECOND EXECUTIVE STANDUP (CINE PROMPT PRO)');
console.log('======================================================\n');

const now = new Date().toISOString();
const dateStr = now.split('T')[0];

const staffProfiles = [
  {
    id: 'gtm-engineer',
    name: 'GTM Engineer',
    icon: '🚀',
    role: 'Tăng trưởng & Phát hành (Go-To-Market)',
    briefFile: path.join(staffDir, 'gtm-engineer', 'brief-latest.md'),
    boardDir: path.join(staffDir, 'gtm-engineer', 'board'),
    fallbackFocus: 'Kiểm toán Vercel deploy, hoàn tất hồ sơ niêm yết Toolify & Futurepedia.'
  },
  {
    id: 'seo-employee',
    name: 'SEO & AEO Employee',
    icon: '🔍',
    role: 'Tối ưu hóa Tìm kiếm & Answer Engine (AEO)',
    briefFile: path.join(staffDir, 'seo-employee', 'brief-latest.md'),
    boardDir: path.join(staffDir, 'seo-employee', 'board'),
    fallbackFocus: 'Tối ưu Schema.org VideoObject, phủ từ khóa "AI video prompt generator", "Midjourney v8 cinematography".'
  },
  {
    id: 'social-media-employee',
    name: 'Social Media Employee',
    icon: '📱',
    role: 'Truyền thông Xã hội & Viral Content',
    briefFile: path.join(staffDir, 'social-media-employee', 'board', 'SOCIAL-BOARD.md'),
    boardDir: path.join(staffDir, 'social-media-employee', 'board'),
    fallbackFocus: 'Phát hành chuỗi 3 bài viết viral cho cộng đồng Vibe Coding & Facebook Video Creators.'
  }
];

const reports = [];

staffProfiles.forEach(emp => {
  let statusSummary = '';
  let blockers = 'Không có rào cản';
  let waitingOn = 'Sẵn sàng triển khai khi có lệnh';

  if (fs.existsSync(emp.briefFile)) {
    const content = fs.readFileSync(emp.briefFile, 'utf-8');
    const lines = content.split('\n').map(l => l.trim()).filter(Boolean);
    const actionLines = lines.filter(l => l.startsWith('- **[Card') || l.startsWith('- [x]') || l.startsWith('- [ ]') || l.startsWith('### '));
    if (actionLines.length > 0) {
      statusSummary = actionLines.slice(0, 3).map(l => '  ' + l.replace(/^###\s*/, '📌 ')).join('\n');
    } else {
      statusSummary = '  📌 ' + (lines[1] || emp.fallbackFocus);
    }

    if (content.includes('Waiting On Member')) {
      const waitPart = content.split('Waiting On Member')[1]?.split('##')[0]?.trim();
      if (waitPart) waitingOn = waitPart.replace(/^[^\n]*\n/, '').trim();
    }
  } else {
    statusSummary = `  📌 ${emp.fallbackFocus}`;
  }

  reports.push({
    ...emp,
    statusSummary,
    blockers,
    waitingOn
  });

  console.log(`${emp.icon} [${emp.name.toUpperCase()}] - ${emp.role}`);
  console.log(`Tiến độ / Việc hôm nay:`);
  console.log(statusSummary);
  console.log(`Chờ duyệt: ${waitingOn.slice(0, 100)}`);
  console.log('------------------------------------------------------\n');
});

// Format Markdown Output
const mdOutput = `# 📋 Báo Cáo Standup 60 Giây — AI Staff (Cine Prompt Pro)
> **Thời gian đồng bộ**: ${now}  
> **Chủ trì**: CEO / Lead Director (Anh Trung)  
> **Tình trạng nhân sự**: 3/3 AI Employees trực tuyến

---

## 🎯 1. Chi Tiết Từng Nhân Sự AI

${reports.map(r => `### ${r.icon} ${r.name} (\`${r.id}\`) — *${r.role}*
- **Trọng tâm công việc**:
${r.statusSummary}
- **Chờ Anh Trung duyệt**: ${r.waitingOn}
- **Rào cản (Blockers)**: ${r.blockers}
`).join('\n')}

---

## ⚡ 2. Việc Cần Anh Trung Quyết Định Ngay (Decision Cards)
1. **[GTM]**: Kiểm tra link Vercel https://cine-prompt-pro.vercel.app/ để xác nhận redeploy phiên bản v2.1.
2. **[Social]**: Duyệt bài viết số 1 (Nhóm "Vibe Coding is Life") trong file \`scratch/ai-staff/social-media-employee/board/SOCIAL-BOARD.md\`.
3. **[SEO]**: Phê duyệt cấu hình Meta tags và Sitemap trong \`seo-employee/AEO-PLAYBOOK.md\`.

---
*Generated by \`scripts/run_standup.mjs\` — Powered by Antigravity IDE Harness Engineering*
`;

try {
  fs.writeFileSync(outputFile, mdOutput, 'utf-8');
  console.log(`✅ Đã lưu biên bản Standup vào: ${outputFile}\n`);
} catch (err) {
  console.error('Lỗi lưu file standup:', err);
}
